spring:
  application:
    microservice_analyzer:
      url: http://localhost:8090/message_analyzer/api/v1/

#spring.datasource.url=jdbc:h2:file:~/h2-db;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
#spring.sql.init.mode=always
